### ISSUE TITLE
HM5157.  Hmailserver winsock 2. There was a communication error with SpamAssassin

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#167] opened 2016-05-02 09:33 UTC
As logged and discussed many times.  Latest discussion with author of Spamassassin (Harald 'Binkle') ruling out Spamassassin as the cause.  Further high level analysis suggesting the cause (code or 'Boost' library), with agreement to look in to, found from here:  https://www.hmailserver.com/forum/viewtopic.php?p=181600#p181600

Boost diagnosis from here: https://www.hmailserver.com/forum/viewtopic.php?p=184625#p184625

>  I have discovered through my proxy program that I, too, occasionally get the socket close notification (or EOF as Boost calls it) BEFORE I have read all the information on the socket. In these circumstances, I can continue reading information from the socket after receiving the close notification (or EOF). So, I'm starting to believe that hMailServer does indeed have a bug.

**Comment by RvdHout** [comment] 2022-08-09 08:25
@martinknafve 

I think i might have found the culprit causing this error, 

TCPConnection::AsyncRead uses transfer_at_least(1), which expect at least 1 byte to be transferred but if no more bytes are transferred as there no more bytes in the (file)stream, this results in the mentioned boost::asio::error::eof (boost error code 2, which is not a winsock error as reported by HMS)

> "DEBUG" 3424 "2015-05-15 16:22:21.717" "Parsing response from SpamAssassin. Session 30202"
> "DEBUG" 3424 "2015-05-15 16:22:21.811" "The read operation failed. **Bytes transferred: 0** Remote IP: 127.0.0.1, Session: 30202, Code: 2, Message: End of file"
> "DEBUG" 3424 "2015-05-15 16:22:21.811" "Ending session 30202"

**Comment by RvdHout** [comment] 2022-08-09 16:44
@martinknafve 
Some workarounds, that might fix this winsock error 2 issue with SA
https://www.hmailserver.com/forum/viewtopic.php?f=7&t=39288&p=241516#p241516

**Comment by RvdHout** [comment] 2022-08-13 08:55
@martinknafve 

Same here, https://github.com/hmailserver/hmailserver/issues/195

There you claim it is not a bug, but it is....  taken that example

`
"DEBUG"	3560	"2017-01-17 11:54:01.446"	"Creating session 204"
"TCPIP"	3560	"2017-01-17 11:54:01.446"	"TCP - xxx.xxx.xxx.xxx connected to xxx.xxx.xxx.xxx:110."
"DEBUG"	3560	"2017-01-17 11:54:01.446"	"TCP connection started for session 197"
"POP3D"	3560	197	"2017-01-17 11:54:01.446"	"xxx.xxx.xxx.xxx"	"SENT: +OK POP3"
"POP3D"	1740	197	"2017-01-17 11:54:01.568"	"xxx.xxx.xxx.xxx"	"RECEIVED: CAPA"
"POP3D"	1740	197	"2017-01-17 11:54:01.568"	"xxx.xxx.xxx.xxx"	"SENT: +OK CAPA list follows[nl]USER[nl]UIDL[nl]TOP[nl]."
"POP3D"	3560	197	"2017-01-17 11:54:01.677"	"xxx.xxx.xxx.xxx"	"RECEIVED: USER user@host.com"
"POP3D"	3560	197	"2017-01-17 11:54:01.677"	"xxx.xxx.xxx.xxx"	"SENT: +OK Send your password"
"POP3D"	2140	197	"2017-01-17 11:54:01.793"	"xxx.xxx.xxx.xxx"	"RECEIVED: PASS ***"
"DEBUG"	2140	"2017-01-17 11:54:01.809"	"Reading messages from database."
"POP3D"	2140	197	"2017-01-17 11:54:01.809"	"xxx.xxx.xxx.xxx"	"SENT: +OK Mailbox locked and ready"
"POP3D"	3372	197	"2017-01-17 11:54:01.940"	"xxx.xxx.xxx.xxx"	"RECEIVED: UIDL"
"POP3D"	3372	197	"2017-01-17 11:54:01.940"	"xxx.xxx.xxx.xxx"	"SENT: +OK 1 messages (3590 octets)[nl]1 1[nl]."
"POP3D"	1740	197	"2017-01-17 11:54:02.058"	"xxx.xxx.xxx.xxx"	"RECEIVED: RETR 1"
"POP3D"	1740	197	"2017-01-17 11:54:02.058"	"xxx.xxx.xxx.xxx"	"SENT: ."
"POP3D"	3108	197	"2017-01-17 11:54:02.733"	"xxx.xxx.xxx.xxx"	"RECEIVED: DELE 1"
"POP3D"	3108	197	"2017-01-17 11:54:02.733"	"xxx.xxx.xxx.xxx"	"SENT: +OK msg deleted"
"DEBUG"	3560	"2017-01-17 11:54:02.857"	"The read operation failed. Bytes transferred: 0 Remote IP: xxx.xxx.xxx.xxx, Session: 197, Code: 2, Message: End of file"
"DEBUG"	3560	"2017-01-17 11:54:02.857"	"Ending session 197"
"DEBUG"	2764	"2017-01-17 11:54:44.161"	"No messages to index."
"DEBUG"	3560	"2017-01-17 11:55:01.255"	"Creating session 205"
"TCPIP"	3560	"2017-01-17 11:55:01.255"	"TCP - xxx.xxx.xxx.xxx connected to xxx.xxx.xxx.xxx:110."
"DEBUG"	3560	"2017-01-17 11:55:01.258"	"TCP connection started for session 204"
"POP3D"	3560	204	"2017-01-17 11:55:01.258"	"xxx.xxx.xxx.xxx"	"SENT: +OK POP3"
"POP3D"	744	204	"2017-01-17 11:55:01.370"	"xxx.xxx.xxx.xxx"	"RECEIVED: CAPA"
"POP3D"	744	204	"2017-01-17 11:55:01.370"	"xxx.xxx.xxx.xxx"	"SENT: +OK CAPA list follows[nl]USER[nl]UIDL[nl]TOP[nl]."
"POP3D"	2140	204	"2017-01-17 11:55:01.501"	"xxx.xxx.xxx.xxx"	"RECEIVED: USER user@host.com"
"POP3D"	2140	204	"2017-01-17 11:55:01.501"	"xxx.xxx.xxx.xxx"	"SENT: +OK Send your password"
"POP3D"	3108	204	"2017-01-17 11:55:01.635"	"xxx.xxx.xxx.xxx"	"RECEIVED: PASS ***"
"POP3D"	3108	204	"2017-01-17 11:55:01.635"	"xxx.xxx.xxx.xxx"	"SENT: +OK Mailbox locked and ready"
"POP3D"	3560	204	"2017-01-17 11:55:01.771"	"xxx.xxx.xxx.xxx"	"RECEIVED: UIDL"
"POP3D"	3560	204	"2017-01-17 11:55:01.771"	"xxx.xxx.xxx.xxx"	"SENT: +OK 1 messages (3590 octets)[nl]1 1[nl]."
"POP3D"	744	204	"2017-01-17 11:55:01.896"	"xxx.xxx.xxx.xxx"	"RECEIVED: RETR 1"
"POP3D"	744	204	"2017-01-17 11:55:01.896"	"xxx.xxx.xxx.xxx"	"SENT: ."
"POP3D"	3372	204	"2017-01-17 11:55:02.203"	"xxx.xxx.xxx.xxx"	"RECEIVED: DELE 1"
"POP3D"	3372	204	"2017-01-17 11:55:02.203"	"xxx.xxx.xxx.xxx"	"SENT: +OK msg deleted"
"DEBUG"	2140	"2017-01-17 11:55:02.507"	"The read operation failed. Bytes transferred: 0 Remote IP: xxx.xxx.xxx.xxx, Session: 204, Code: 2, Message: End of file"
"DEBUG"	2140	"2017-01-17 11:55:02.507"	"Ending session 204"
`

this line:

`"DEBUG"	2140	"2017-01-17 11:55:02.507"	"The read operation failed. Bytes transferred: 0 Remote IP: xxx.xxx.xxx.xxx, Session: 204, Code: 2, Message: End of file"
`

Means nothing more than the fact the end of the file is reached, eg: the mentioned boost::asio::error::eof = 2
There was no 'real' error whatsoever and therefor there is no need to disconnect and (end and) start new a session

**Comment by RvdHout** [comment] 2022-08-13 09:58
Maybe something like this?

```
   TCPConnection::AsyncReadCompleted(const boost::system::error_code& error, size_t bytes_transferred)
   {
      UpdateAutoLogoutTimer();

      if (error.value() != 0)
      {
         if (connection_state_ != StateConnected)
         {
            // The read failed, but we've already started the disconnection. So we should not log the failure
            // or enqueue a new disconnect.
            return;
         }

         if (error.value() == boost::asio::error::eof)
         {
            // Ignore end_of_stream error, there may still be data in the receive buffer we can read.
            return;
         }

         OnReadError(error.value());

         ... 

```

**Comment by RvdHout** [comment] 2022-08-13 12:45
Damn, still getting error because SpamTestSpamAssassin::RunTest doesn't complete :(

`"ERROR"	1224	"2022-08-13 13:22:10.218"	"Severity: 2 (High), Code: HM5508, Source: SpamTestSpamAssassin::RunTest, Description: The SpamAssassin tests did not complete. Please confirm that the configuration (host name and port) is valid and that SpamAssassin is running."`

I know for sure i am near to the cause of this annoying winsock error 2, but i'm a bit out of ideas how to solve it, suggestions?

**Comment by martinknafve** [comment] 2023-03-12 16:16
PT merged

**Closed by martinknafve** 2023-03-12 16:16 UTC
