### ISSUE TITLE
hMail is duplicating Emails if you change the Subject of the Mail

### ISSUE THREAD

**Issue by fagopon** [hmailserver/hmailserver#345] opened 2020-07-30 13:59 UTC
If you change the Subject of a Mail in Outllook 2013 or newer hMail starts imidiately duplicating the Email. It only stops if Outlook was closed.

**Comment by mstenz** [comment] 2020-07-30 14:02
It not only do this in this case. also when Drafts get changed and outlook updeates the draft hmail will create a new copy, means in outlook for some seconds you see 2 emails, one will go away directly. this behaviour also gives issues on my end very often. 
But i don#t understand what you mean with "it stopsif outlook is closed", this is normally a one time activity and for sure you cannot rename a email when outlook is closed.

**Comment by fagopon** [comment] 2020-07-30 14:56
You misunderstood me.
The duplicating process ist starting if you change the Subject of an existing Email, or an Outlook Addin will do this. One case is a AV or a Spamfilter that add something to the subject line of the email.

If this happen Outlook is starting to duplicating this Email. Now you can get thousands of the same Email. The duplicating process stops if you close Outlook an restart it. I will upload an Screenshot tomorrow when i am back in the Office.

**Comment by mstenz** [comment] 2020-07-30 17:24
I cannot reproduce this when i manually edit the email (i have tested with subject) and using Outlook M365 Version 2006 (Build 13001.20384)

**Comment by fagopon** [comment] 2020-07-31 07:17
Dear mstenz. I forgot to say. Its IMAP how Outlook is connected to hMail. Maybe it happens only if more than one Client is connected to the IMAP Account. I try to figure it out. We can reproduce it here easy.

**Comment by fagopon** [comment] 2020-07-31 07:38
Allright. Here we go. I testet it on a fresh hMail Install hMailServer-5.6.7-B2425. I connectet one Office 2016 Version 2006 Build 13001.20384 (Click to run)
Duplication starts immidiatly after changing the subject line an hit the save button. Duplication stops only if you close Outlook.

![hMail Test1](https://user-images.githubusercontent.com/69002214/89011861-72136580-d311-11ea-9619-9a7baf1d3d5a.JPG)
![hMail Test2](https://user-images.githubusercontent.com/69002214/89011866-73449280-d311-11ea-95d5-6bd09cdcbe79.JPG)

**Comment by mstenz** [comment] 2020-07-31 10:18
Can you try to set everything to debug and then reproduce it and share the logfile. maybe there is any glue in IMAP messages. I think thats the only way to check further, but i am not the expert here, so someone else need to have a look.

**Comment by thikarp** [comment] 2021-11-11 09:26
I have the same problem. Evgertime the subject line is changed, I get hundreds of copies. Was this solved? 
If not I can present a logfile.

**Comment by fagopon** [comment] 2021-11-11 10:31
The problem is not solved. And there are other problems like dealing with Emails bigger 25MB (IMAP). hMail is a great Project. But that two Problems are big for our customers. So we finally decided to switch these customers to another Mailserver Software. (MDaemon)

**Comment by SorenRR** [comment] 2021-11-11 11:53
> The problem is not solved. And there are other problems like dealing with Emails bigger 25MB (IMAP). hMail is a great Project. But that two Problems are big for our customers. So we finally decided to switch these customers to another Mailserver Software. (MDaemon)

I believe you were asked on 31. Jul 2020 to produce a debug log from hMailServer to help solve the duplication problem. Where did you upload this log?

**Comment by RvdHout** [comment] 2021-11-11 12:32
I also can reproduce this, every renamed message is duplicated **once**... i don't get hundreds like a few people reported above?
Is that correct? Eg: looks like a new message is created and the old message is not deleted.

How much sense makes it to change the subject on a received message anyway? 
Outlook has built-in features to move, followup, or mark messages

**Comment by OutbackMatt** [comment] 2021-11-11 12:35
Is there a problem with mail messages bigger than 25 MB?
I don't recall that, and I certainly often send myself multiple 12 Megapixel photos from my iphone to my main address.

In fact I just successfully sent 18 photos with a total size of 40 MB - sent via my home wifi (I use IMAP on my phone and my desktop)

**Comment by thikarp** [comment] 2021-11-11 12:46
I have only the problem, when the subject is changed. Here my AV scanner from securepoint marks a message with "****** Spam ******". After this mark the message will be duplicated until I stop it by closing Outlook or switching to another folder. 

If I connect e.g. a google account, it doesn't matter when I change the subject. The problem must be in communication between hmail and outlook.

**Comment by RvdHout** [comment] 2021-11-11 12:52
I see now, looks like hmailserver is not updating existing message but makes a copy, right? 
I noticed this because the changed message also arrived in (once again) in my POP3 box as well as unread message

**Comment by RvdHout** [comment] 2021-11-11 13:16
@martinknafve 
This is easy to reproduce, any idea what is wrong/going on there?

**Comment by martinknafve** [comment] 2021-11-28 10:42
The issue appears to occur because hMailServer does not support the UIDPLUS extension. As far as I can tell, it's a bug in Outlook, most likely caused by the fact that most IMAP servers supports UIDPLUS and they didn't test on non-UIDPLUS servers.

I implemented a very partial support for UIDPLUS and the issue went away. Took some time to figure out, since I don't have the source code for Outlook... After a message is added to the Drafts folder, Outlook lists messages on the server which causes the duplicate to appear. On the server, there is just 1 message, but Outlook thinks that there are 2, probably since it added 1 and the server returned 1. When UIDPLUS is implemented, the server will give Outlook a unique identifier of the message after it has been added, and when Outlook receives that it will not ask the server for a list of messages.

**Comment by mstenz** [comment] 2021-11-28 11:11
Probably that fixes my issue with Draft Message I have still since years with hmailserver, as it duplicates the message most probably and then the file is corrupted after some minutes of editing.

**Comment by RvdHout** [comment] 2021-11-29 19:40
@martinknafve 
I assume that partial support for UIDPLUS not only fixes the drafts folder issue but also the subject changing/renaming issue?

**Comment by martinknafve** [comment] 2021-11-29 19:48
As far as I can tell, yes. It's not really possible to implement only partial support of UIDPLUS though. That would probably make it stop working with some clients, since support for UIDPLUS adds a couple of new features and if the server announces support for UIDPLUS but then doesn't implement all of them, then it's a bit broken.

For example, UIDPLUS brings a new command (UID EXPUNGE), and modify the response of COPY/UID COPY/APPEND commands. There is also some special logic when dealing with shared folders (when appending/copying to a shared folder, the server should not send some data if the user does not have access to read that folder).

**Comment by martinknafve** [comment] 2021-11-29 20:02
@RvdHout, if you want you can give the version in the branch feature/uidplus-345 a try. It implements the various parts of UIDPLUS. Its not production ready but the test suite passes (I added new tests for uidplus as well.)

I skimmed through the spec again and I don't see anything missing, but I think I need to run some basic regression tests with various clients and see that nothing obvious is broken.

**Comment by RvdHout** [comment] 2021-11-30 05:38
Initial test result look good, Outlook 2019 (16.0.10380.20037) 64-bits doing same steps i did before 👍

**Comment by RvdHout** [comment] 2021-11-30 05:54
Outlook 2021 LTSC (16.0.14332.2102) 64-bits gives some undesired result, seems to loop after changing the subject 

```
"DEBUG"	4500	"2021-11-30 06:51:17.620"	"Saving message: {B3EFD527-F5A3-4BB7-97AA-ECD9D9A9CF61}.eml"
"DEBUG"	4500	"2021-11-30 06:51:17.636"	"Reading messages from database."
"IMAPD"	4500	69	"2021-11-30 06:51:17.636"	"XXX-XXX-XXX-XXX"	"SENT: * 3 EXISTS[nl]* 57 RECENT[nl]arp6 OK [APPENDUID 1404303446 4812] APPEND completed"
"IMAPD"	4500	69	"2021-11-30 06:51:17.636"	"XXX-XXX-XXX-XXX"	"RECEIVED: xjc9 IDLE"
"IMAPD"	4500	69	"2021-11-30 06:51:17.636"	"XXX-XXX-XXX-XXX"	"SENT: + idling"
"IMAPD"	6048	69	"2021-11-30 06:51:17.636"	"XXX-XXX-XXX-XXX"	"RECEIVED: DONE"
"IMAPD"	6048	69	"2021-11-30 06:51:17.636"	"XXX-XXX-XXX-XXX"	"SENT: xjc9 OK IDLE terminated"
"IMAPD"	3092	69	"2021-11-30 06:51:17.636"	"XXX-XXX-XXX-XXX"	"RECEIVED: tdpv NOOP"
"IMAPD"	3092	69	"2021-11-30 06:51:17.636"	"XXX-XXX-XXX-XXX"	"SENT: tdpv OK NOOP completed"
"IMAPD"	4500	69	"2021-11-30 06:51:17.651"	"XXX-XXX-XXX-XXX"	"RECEIVED: wls0 UID STORE 4811 +FLAGS.SILENT (\Deleted \Seen)"
"IMAPD"	4500	69	"2021-11-30 06:51:17.651"	"XXX-XXX-XXX-XXX"	"SENT: wls0 OK UID completed"
"IMAPD"	4500	69	"2021-11-30 06:51:17.651"	"XXX-XXX-XXX-XXX"	"RECEIVED: qtnv IDLE"
"IMAPD"	4500	69	"2021-11-30 06:51:17.651"	"XXX-XXX-XXX-XXX"	"SENT: + idling"
"IMAPD"	3092	69	"2021-11-30 06:51:17.651"	"XXX-XXX-XXX-XXX"	"RECEIVED: DONE"
"IMAPD"	3092	69	"2021-11-30 06:51:17.651"	"XXX-XXX-XXX-XXX"	"SENT: qtnv OK IDLE terminated"
"IMAPD"	4500	69	"2021-11-30 06:51:17.651"	"XXX-XXX-XXX-XXX"	"RECEIVED: za70 UID EXPUNGE 4811"
"DEBUG"	4500	"2021-11-30 06:51:17.651"	"Deleting message"
"DEBUG"	4500	"2021-11-30 06:51:17.651"	"Deleting message file."
"IMAPD"	4500	69	"2021-11-30 06:51:17.667"	"XXX-XXX-XXX-XXX"	"SENT: * 2 EXPUNGE"
"IMAPD"	4500	69	"2021-11-30 06:51:17.667"	"XXX-XXX-XXX-XXX"	"SENT: za70 OK UID EXPUNGE Completed"
"IMAPD"	4500	69	"2021-11-30 06:51:17.667"	"XXX-XXX-XXX-XXX"	"SENT: za70 OK UID completed"
"IMAPD"	6048	69	"2021-11-30 06:51:17.714"	"XXX-XXX-XXX-XXX"	"RECEIVED: 3u76 IDLE"
"IMAPD"	6048	69	"2021-11-30 06:51:17.714"	"XXX-XXX-XXX-XXX"	"SENT: + idling"
"IMAPD"	3092	69	"2021-11-30 06:51:17.714"	"XXX-XXX-XXX-XXX"	"RECEIVED: DONE"
"IMAPD"	3092	69	"2021-11-30 06:51:17.714"	"XXX-XXX-XXX-XXX"	"SENT: 3u76 OK IDLE terminated"
"IMAPD"	3092	69	"2021-11-30 06:51:17.714"	"XXX-XXX-XXX-XXX"	"RECEIVED: z28g UID FETCH 4813:4294967295 (UID FLAGS RFC822.SIZE BODY.PEEK[] INTERNALDATE)"
"IMAPD"	3092	69	"2021-11-30 06:51:17.714"	"XXX-XXX-XXX-XXX"	"SENT: z28g OK UID completed"
"IMAPD"	3092	69	"2021-11-30 06:51:17.714"	"XXX-XXX-XXX-XXX"	"RECEIVED: ii71 IDLE"
"IMAPD"	3092	69	"2021-11-30 06:51:17.714"	"XXX-XXX-XXX-XXX"	"SENT: + idling"
"IMAPD"	3092	69	"2021-11-30 06:51:19.261"	"XXX-XXX-XXX-XXX"	"RECEIVED: DONE"
"IMAPD"	3092	69	"2021-11-30 06:51:19.261"	"XXX-XXX-XXX-XXX"	"SENT: ii71 OK IDLE terminated"
"IMAPD"	6048	69	"2021-11-30 06:51:19.261"	"XXX-XXX-XXX-XXX"	"RECEIVED: 1mst APPEND "INBOX" (\Seen) "30-Nov-2021 06:42:32 +0100" {1499}"
"IMAPD"	6048	69	"2021-11-30 06:51:19.261"	"XXX-XXX-XXX-XXX"	"SENT: + Ready for literal data"
"DEBUG"	4500	"2021-11-30 06:51:19.261"	"Saving message: {DEC60530-CF70-4C9F-BE89-9816D228B2DF}.eml"
"DEBUG"	4500	"2021-11-30 06:51:19.277"	"Reading messages from database."
"IMAPD"	4500	69	"2021-11-30 06:51:19.277"	"XXX-XXX-XXX-XXX"	"SENT: * 3 EXISTS[nl]* 58 RECENT[nl]1mst OK [APPENDUID 1404303446 4813] APPEND completed"
"IMAPD"	4500	69	"2021-11-30 06:51:19.277"	"XXX-XXX-XXX-XXX"	"RECEIVED: nq6g IDLE"
"IMAPD"	4500	69	"2021-11-30 06:51:19.277"	"XXX-XXX-XXX-XXX"	"SENT: + idling"
"IMAPD"	3092	69	"2021-11-30 06:51:19.277"	"XXX-XXX-XXX-XXX"	"RECEIVED: DONE"
"IMAPD"	3092	69	"2021-11-30 06:51:19.277"	"XXX-XXX-XXX-XXX"	"SENT: nq6g OK IDLE terminated"
"IMAPD"	4500	69	"2021-11-30 06:51:19.277"	"XXX-XXX-XXX-XXX"	"RECEIVED: jrvg NOOP"
"IMAPD"	4500	69	"2021-11-30 06:51:19.277"	"XXX-XXX-XXX-XXX"	"SENT: jrvg OK NOOP completed"
"IMAPD"	6048	69	"2021-11-30 06:51:19.277"	"XXX-XXX-XXX-XXX"	"RECEIVED: isfu UID STORE 4812 +FLAGS.SILENT (\Deleted \Seen)"
"IMAPD"	6048	69	"2021-11-30 06:51:19.277"	"XXX-XXX-XXX-XXX"	"SENT: isfu OK UID completed"
"IMAPD"	9060	69	"2021-11-30 06:51:19.292"	"XXX-XXX-XXX-XXX"	"RECEIVED: 4g4w IDLE"
"IMAPD"	9060	69	"2021-11-30 06:51:19.292"	"XXX-XXX-XXX-XXX"	"SENT: + idling"
"IMAPD"	4500	69	"2021-11-30 06:51:19.292"	"XXX-XXX-XXX-XXX"	"RECEIVED: DONE"
"IMAPD"	4500	69	"2021-11-30 06:51:19.292"	"XXX-XXX-XXX-XXX"	"SENT: 4g4w OK IDLE terminated"
"IMAPD"	6048	69	"2021-11-30 06:51:19.292"	"XXX-XXX-XXX-XXX"	"RECEIVED: 0aci UID EXPUNGE 4812"
"DEBUG"	6048	"2021-11-30 06:51:19.292"	"Deleting message"
"DEBUG"	6048	"2021-11-30 06:51:19.292"	"Deleting message file."
"IMAPD"	6048	69	"2021-11-30 06:51:19.292"	"XXX-XXX-XXX-XXX"	"SENT: * 2 EXPUNGE"
"IMAPD"	6048	69	"2021-11-30 06:51:19.292"	"XXX-XXX-XXX-XXX"	"SENT: 0aci OK UID EXPUNGE Completed"
"IMAPD"	6048	69	"2021-11-30 06:51:19.292"	"XXX-XXX-XXX-XXX"	"SENT: 0aci OK UID completed"
"IMAPD"	6048	69	"2021-11-30 06:51:19.339"	"XXX-XXX-XXX-XXX"	"RECEIVED: slah IDLE"
"IMAPD"	6048	69	"2021-11-30 06:51:19.339"	"XXX-XXX-XXX-XXX"	"SENT: + idling"
"IMAPD"	6048	69	"2021-11-30 06:51:19.355"	"XXX-XXX-XXX-XXX"	"RECEIVED: DONE"
"IMAPD"	6048	69	"2021-11-30 06:51:19.355"	"XXX-XXX-XXX-XXX"	"SENT: slah OK IDLE terminated"
"IMAPD"	9060	69	"2021-11-30 06:51:19.355"	"XXX-XXX-XXX-XXX"	"RECEIVED: zpd7 UID FETCH 4814:4294967295 (UID FLAGS RFC822.SIZE BODY.PEEK[] INTERNALDATE)"
"IMAPD"	9060	69	"2021-11-30 06:51:19.355"	"XXX-XXX-XXX-XXX"	"SENT: zpd7 OK UID completed"
"IMAPD"	9060	69	"2021-11-30 06:51:19.355"	"XXX-XXX-XXX-XXX"	"RECEIVED: 18xv IDLE"
"IMAPD"	9060	69	"2021-11-30 06:51:19.355"	"XXX-XXX-XXX-XXX"	"SENT: + idling"
"IMAPD"	6048	69	"2021-11-30 06:51:20.886"	"XXX-XXX-XXX-XXX"	"RECEIVED: DONE"
"IMAPD"	6048	69	"2021-11-30 06:51:20.886"	"XXX-XXX-XXX-XXX"	"SENT: 18xv OK IDLE terminated"
"IMAPD"	4500	69	"2021-11-30 06:51:20.886"	"XXX-XXX-XXX-XXX"	"RECEIVED: e22c APPEND "INBOX" (\Seen) "30-Nov-2021 06:42:32 +0100" {1499}"
"IMAPD"	4500	69	"2021-11-30 06:51:20.886"	"XXX-XXX-XXX-XXX"	"SENT: + Ready for literal data"
"DEBUG"	6048	"2021-11-30 06:51:20.886"	"Saving message: {DE076556-543A-41BF-ACCD-600D4612AAF6}.eml"
"DEBUG"	6048	"2021-11-30 06:51:20.902"	"Reading messages from database."
"IMAPD"	6048	69	"2021-11-30 06:51:20.902"	"XXX-XXX-XXX-XXX"	"SENT: * 3 EXISTS[nl]* 59 RECENT[nl]e22c OK [APPENDUID 1404303446 4814] APPEND completed"
"IMAPD"	4500	69	"2021-11-30 06:51:20.902"	"XXX-XXX-XXX-XXX"	"RECEIVED: egbf IDLE"
"IMAPD"	4500	69	"2021-11-30 06:51:20.902"	"XXX-XXX-XXX-XXX"	"SENT: + idling"
"IMAPD"	4500	69	"2021-11-30 06:51:20.902"	"XXX-XXX-XXX-XXX"	"RECEIVED: DONE"
"IMAPD"	4500	69	"2021-11-30 06:51:20.902"	"XXX-XXX-XXX-XXX"	"SENT: egbf OK IDLE terminated"
"IMAPD"	4500	69	"2021-11-30 06:51:20.902"	"XXX-XXX-XXX-XXX"	"RECEIVED: u29b NOOP"
"IMAPD"	4500	69	"2021-11-30 06:51:20.902"	"XXX-XXX-XXX-XXX"	"SENT: u29b OK NOOP completed"
"IMAPD"	9060	69	"2021-11-30 06:51:20.917"	"XXX-XXX-XXX-XXX"	"RECEIVED: 6xo3 UID STORE 4813 +FLAGS.SILENT (\Deleted \Seen)"
"IMAPD"	9060	69	"2021-11-30 06:51:20.917"	"XXX-XXX-XXX-XXX"	"SENT: 6xo3 OK UID completed"
"IMAPD"	6048	69	"2021-11-30 06:51:20.917"	"XXX-XXX-XXX-XXX"	"RECEIVED: 7l0q IDLE"
"IMAPD"	6048	69	"2021-11-30 06:51:20.917"	"XXX-XXX-XXX-XXX"	"SENT: + idling"
"IMAPD"	4500	69	"2021-11-30 06:51:20.917"	"XXX-XXX-XXX-XXX"	"RECEIVED: DONE"
"IMAPD"	4500	69	"2021-11-30 06:51:20.917"	"XXX-XXX-XXX-XXX"	"SENT: 7l0q OK IDLE terminated"
"IMAPD"	9060	69	"2021-11-30 06:51:20.917"	"XXX-XXX-XXX-XXX"	"RECEIVED: scrt UID EXPUNGE 4813"
"DEBUG"	9060	"2021-11-30 06:51:20.917"	"Deleting message"
"DEBUG"	9060	"2021-11-30 06:51:20.917"	"Deleting message file."
```

It keeps repeating this until you move away to another imap folder and/or close and restart Outlook

**Comment by RvdHout** [comment] 2021-11-30 07:38
Outlook 2021 really is acting weird, looping stops as soon as you move away from the INBOX. But even closing and restarting outlook does seem to trigger this behavior, clueless...

![Animatie](https://user-images.githubusercontent.com/13403301/144005299-d371471a-a2a8-47ba-9e11-103b618d8fd0.gif)

**Comment by martinknafve** [comment] 2021-11-30 07:42
Thanks. I will try this myself as well. 

As I indicated I need to run some regression tests. I see in the log that Outlook uses the new UID EXPUNGE command and it could be I got that one wrong. The spec was quite short and didn't give so many details. I'll probably compare the behavior in hMailServer with another server and see if they differ.

**Comment by RvdHout** [comment] 2021-11-30 08:34
On another instance using outlook 2019 (16.0.10380.20037) 64-bits i am unable to change the subject as described in this post: https://github.com/hmailserver/hmailserver/issues/345#issuecomment-666982113 

This is really confusing....on a VM using outlook 2019 (16.0.10380.20037) 64-bits with a single IMAP mailbox i am able to change the subject as described above. But on my main pc using the very same outlook 2019 (16.0.10380.20037) 64-bits i am not (this outlook instance contains a few pop3 accounts and a hotmail account as well so perhaps that is the reason it won't let me edit the subject)

**Comment by RvdHout** [comment] 2021-12-02 08:53
**Outlook 2019 (16.0.10380.20037) 64-bits (Click-to-Run)**
Without UIDPLUS -> Message gets visually duplicated in list (until you update the view)
With UIDPLUS -> Message does not get duplicated in the view

**Outlook 2021 LTSC (16.0.14332.20143) 64-bits (Click-to-Run)**
Without UIDPLUS -> Message gets physically duplicated on the server (eg: loops = multiple times!), not only the list (until you update the view)
With UIDPLUS -> Message does not get duplicated, but the loop still occurs

**Comment by martinknafve** [comment] 2021-12-04 09:54
I tried using "_Microsoft® Outlook® 2021 MSO (Version 2110 Build 16.0.14527.20270) 64-bit_" but did not get the same issue. This semes to be a later version than the one you're using, but I doubt that it's really related to that. But just to be sure, where did you get hold of that specific version? It's not available for me to download via my Visual Studio subscription it seems.

**Comment by RvdHout** [comment] 2021-12-04 10:35
I downloaded this version as test with the Office Deployment Tool, https://www.microsoft.com/en-us/download/details.aspx?id=49117

first run:
setup /download configuration-Office2021Enterprise.xml

after completion, run:
setup /configure configuration-Office2021Enterprise.xml

**Comment by RvdHout** [comment] 2021-12-06 12:46
FYI, this loop seems not not happening with a message in "drafts" folder, but only when changing the subject of a message in the "inbox" folder described [here](https://github.com/hmailserver/hmailserver/issues/345#issuecomment-666982113)

**Comment by fagopon** [comment] 2021-12-06 14:13
> FYI, this loop seems not not happening with a message in "drafts" folder, but only when changing the subject of a message in the "inbox" folder described [here](https://github.com/hmailserver/hmailserver/issues/345#issuecomment-666982113)
> 
> edit, this looks similar to what i am experiencing https://answers.microsoft.com/en-us/outlook_com/forum/all/changing-an-email-subject-line-starts-a-cycle-of/21dc9eb8-964a-41de-92c7-d7d0168aadcc

The duplication is also happening in subfolders. But i am testet not was happens in Special Folders like Drafts.

**Comment by RvdHout** [comment] 2021-12-06 14:15
@fagopon, this post was directed to @martinknafve using a special test build using UIDPLUS extension

**Comment by fagopon** [comment] 2021-12-06 14:20
Im sorry. You tagged my comment :)

**Comment by RvdHout** [comment] 2021-12-06 14:50
@fagopon 

Did you have a look at the ms link posted above? That loop issue discussed there seems to be something you referenced to in the initial problem description.

the build with UIDPLUS extension seems to fix the **physical duplication** issue, although i still see some strange things in my logs due the above mentioned loop

**Comment by RvdHout** [comment] 2022-01-09 07:06
@martinknafve
Any progress? Have you been able to reproduce the behavior described above, eg: repeating/looping commands?

**Comment by martinknafve** [comment] 2022-01-15 13:01
I was able to reproduce the issue but not find anything in the hMailServer behavior which would trigger it. I also was able to reproduce the exact same issue with Gmail, so I think it's reasonable to say that it's a bug in Outlook when editing messages in inbox, rather than a bug in hMailServer.

**Comment by RvdHout** [comment] 2022-01-15 13:05
Luckily with the UIDPLUS extension the file is not copied (duplicated) over and over 😉

**Closed** 2023-03-12 13:09 UTC

**Comment by RvdHout** [comment] 2023-03-17 10:11
Not going to implement UIDPLUS? 
With UIDPLUS Message no longer get physically duplicated (in my tests)
