### ISSUE TITLE
Make available a new function that reset the Backup status

### ISSUE THREAD

**Issue by mstenz** [hmailserver/hmailserver#362] opened 2021-03-16 07:41 UTC
Sometimes it is possible the backup crashes for whatever reasons. For example: #163
A new button (+com api) that can reset the status without the need of rebooting hmailserver would make it better as well.

**Comment by martinknafve** [comment] 2023-03-12 13:10
The issue should be fixed by fixing the backup issue (root cause), rather than implementing a button which user has to click.

**Closed by martinknafve** 2023-03-12 13:10 UTC
