### ISSUE TITLE
Mails in Draft get not removed after successfull send

### ISSUE THREAD

**Issue by mstenz** [hmailserver/hmailserver#266] opened 2018-08-13 17:21 UTC
Hi, 

very often (but not always) the mails in draft folder get not deleted after sending successfully the email. 
This is same as in https://www.hmailserver.com/forum/viewtopic.php?t=26501 but i am using Outlook 2016. This just started when using htmailserver with same account on same server that used different mailserver application before. 
I am using IMAP. This happens for all users. As it was working with different mailserver before it must be an issue with hmailserver. 
I have not found any hint why sometimes it is working and sometimes not. I would say 1 of 3 times on my system this issue occours. 
As it seems a lot of users have this issues (see threads in the forum) i assume it would be easy to replicate.

**Comment by jimimaseye** [comment] 2018-08-25 10:41
Hmailserver only deleted/removes when it is told to by the email client.  If its not being removed then the issue is with the client.

No case to answer (IMO).

**Comment by mstenz** [comment] 2018-08-25 11:08
That is not the correct answer. As i have said with same Client but other IMAP Server this is working just out of the box. There is always something in between. It is really worth to look at that issue as it must occour for thousands of users of hmailserver.

**Comment by mstenz** [comment] 2018-08-26 18:49
I am not so sure, Do you have any evidence that it is a client issue? On the other hand any evidence it is not a server issue? As long noone checks whats really happens (unfortunately I cannot do this as there is not enough knowledge available) nobody knows what exactly causing this issue. With this exactly same Outlook Installation I have used in the past more than 5 different mailservers (also some at same time) with different accounts. Some hosted by me, some by others there was never any issue with not deleted Draft messages. This just appeared when starting to use hmailserver. The problem is that this is not happening once a month or year, its happening daily, hourly (depends on how many messages you write). If you use it as main mail system and write 100 mails or more every day it get starting to suck very fast.

**Comment by OutbackMatt** [comment] 2018-08-26 23:11
Evidence that this IS NOT a server issue.
It doesn't happen to RvdHout, to jimimaseye, nor to me.
In more than 10 years moderating the user forum, no-one has reported this.

That you use Outlook. Outlook is really terrible with IMAP, and newer version tend to be much worse.

If you have some logs to support your claim , or any details of the thousands of users that you believe have this issue, then please post that detail to the user forum. This is not the correct place to raise such issues until they have been confirmed.

Evidence that this IS A SERVER ISSUE
The word of a single user who in their own words 'I cannot do this as there is not enough knowledge available'

**Comment by mstenz** [comment] 2018-08-27 09:17
> In more than 10 years moderating the user forum, no-one has reported this.
hmailserver forum is full with this reports. please just search for "draft" there are many reportings of this behaviour together with hmailserver and Outlook. 
Please also check this link: https://social.technet.microsoft.com/Forums/Lync/en-US/312709a5-1f13-4803-bd36-1d6feb166311/outlook-2016-and-imap-duplicate-drafts-generated-in-drafts-folder?forum=outlook 
Nobody is perfect - this also happens for software like Outlook. What i mean that i have not enough knowledge is about the Code of hmailserver as i am not a developer. And i have reported this issue directly here because it is right now only in the forum and it seems no real developer looks at this issue. 
Also that Outlook is bad with IMAP is not correct. Thunderbird is worse as well. I wanted to migrate my mailbox with thunderbird and it was totally catastraphe. Moving thousands (50000+) of objects arround in IMAP with Outlook is just a smooth operation while in Thunderbird not really good experience. (but thats not the problem here).
I really hope that some developer looks to that issue as it is really happening.

**Comment by OutbackMatt** [comment] 2018-08-27 10:08
http://www.hmailserver.com/forum/search.php?keywords=%2Bdraft+%2Bnot+%2Bdeleted&terms=all&author=&sc=1&sf=all&sr=posts&sk=t&sd=d&st=0&ch=300&t=0&submit=Search

112 results going back to early 2007
Not one of them is about draft messages not being deleted, but they all contain the words 'draft' 'not' and 'deleted', never togather.

The post you link to isn't on the hMailserver forum. It's on the outlook forum, and Outlook is NOT standards compliant.

If you have some logs and screen shots - then present them (ON THE USER FORUM) please.
This will give some credence to the claim, and then 'some developer' may well look into the issue. Making vague unsupported claims is just wasting everyone's time.

**Comment by mstenz** [comment] 2018-08-27 13:25
I don't have any logs as this is a production system and if i enable logs there will be Gigabytes of logfiles written in very short timeframe.
But as per the post on the Mircosoft site it seems this has something to do with encodings. That is also very likely as my Drafts folder (and also any other Drafts folder for all Germany users) is called "Entwürfe". This is showed as "Entw&APw-rfe" in the hmailsever Database. Same happens for "Gelöschte Elemente" (Trash), which is "Gel&APY-schte Elemente" in the DB.

**Comment by mstenz** [comment] 2018-12-18 16:20
Any help we can get on this. I even would pay someone to have a look at this. 
The main users complaining about this issue are from Germany so i assume this has something to do with Enconding and "Umlauts". This is definitive a Server issue and before i am rolling out this to more clients the issue need to be fixed.

**Comment by mstenz** [comment] 2019-01-02 17:13
@Dravion If you have a testing installation of hmailserver available i can also use it with my client if this helps you. I only have a production environment running that is too noisy for debugging.

**Comment by Dravion** [comment] 2019-01-03 08:31
Not so fast ;-)
Right now i do a major rewrite of hMailServer which solves a lot of Problems (IMAP included).
This Version of hMailServer will run on Linux, FreeBSD, OpenBSD, MacOS and of course Windows
(Windows Nano-Server included). In fact it should also build on Solaris, HP-UX and IBM AIX but this has to test someone else.

The Question is if this version is for you.
Some features you might depend on wont work at all. For example VBScript is gone and will not return again. Instead it will be LUA,, because its small and better to maintain.Database wise we will re-enable PostgreSQL first and later SQLLite, MariaDB, MySQL and MS-SQL.

**Comment by mstenz** [comment] 2019-01-03 12:04
A linux version would be really great, BUT i use no posgreSQL. Mysql (or in fact Percona on my side) is really the DB # 1. 
Since the start of the year the issues with hmailserver have increased drastically: sometimes sent emails are not stored in Sent folder, sometimes emails gets duplicated 3-50 times just randomly in different folders. 
Will you do this in the environment of hmailserver or name it different and in seperate repo? You can also contact me privately to discuss more things if you want.

**Comment by OutbackMatt** [comment] 2019-01-03 20:46
Again, I know that you don't like hearing this, but NO-ONE ELSE is having this issue.
It seems unreasonable that since the start of they year the frequency of this is increasing for you, if you've made no software changes.

If you can't collect logs from a live system the you aren't trying. Many of us MUST keep some logs to meet government regulations.

**Comment by mstenz** [comment] 2019-01-03 21:38
Hi @OutbackMatt, are you using Umlauts? I assume no, because it seems this issue does only occours then. And about the more issue that are arrising, this is just what happens and there is nothing that can be changed about this fact. 
I CAN and do collect logs, but it is mostly impossible to read them and do correct debugging because if i would enable debugging just 10 minutes the logfile would be in size of many gigabites.

**Comment by OutbackMatt** [comment] 2019-01-03 22:05
No I don't use Umaluts, however MANY hMailserver users do. NO-ONE else reports this issue.

**Comment by mstenz** [comment] 2019-01-04 02:36
if one report it is enough. btw: since months there are no registration in the hmailserver forum possible anymore so there is no one that report it there really. also not all users take the effort as I do and report it here. 
I have seen all your comments in other issues as well and it seems you are not treating other reports seriously as it should be. I really would appreciate the reports of other users and not try to silence them.

**Comment by OutbackMatt** [comment] 2019-01-04 03:20
And now you are being a dick...

The forum certainly allows new registrations, we get many each week.
And it is correct that I don't treat unsubstantiated reports seriously. More often than not when a single user has an issue that affects only them, it is something in their environment that causes the issue.

You can't show logs, and you want us to trust that the issues that you (and only you) see are real.

It is all a bit of a stretch.
Perhaps you should ask for a full refund of your purchase price, and change to another product.
Oh wait, hMailserver is free and open source. Bit hard to get a refund when you don't actually pay for anything. 

And for the record, I am very supportive of issues when they can be shown to be correct.

**Comment by jimimaseye** [comment] 2019-01-04 08:08
Glossing over the insults and personal attacks, I think it's time to make a distinction in the report which gives reason for Matts doubt and the cause for lack of progression/acceptance.  In the opening report, I quote:

"very often ( *but not always* ) the mails in draft folder get not deleted

I would say 1 of 3 times on my system this issue occours."

You then go on to say:
"That is also very likely as my Drafts folder (and also any other Drafts folder for all Germany users) is called "Entwürfe". This is showed as "Entw&APw-rfe" in the hmailsever Database. Same happens for "Gelöschte Elemente" (Trash), which is "Gel&APY-schte Elemente" in the DB."

Well, if it was due to umlauts, then the issue would occur EVERY TIME.  Nothing would be written to these folders and nothing would ever get moved to Trash folder, without fail, as the folder names are constant (once created, they remain).

Matt made a valid request for evidence from logs which would help identify the cause (to prove its umlauts or whatever else the problem may be). Only when we see some diagnostic evidence are we able to look in to the issue with a view for rectifying it.  You cant ring the doctor and say "it hurts sometimes when I do this" and then not actually go to let him SEE the bit that hurts, examine it and then prescribe a cure.

Logs are long when set to debug, yes, but given that you say this happens so often Im sure that enabling logging for 1 minute whilst you replicate the problem will not be so large that you cant examine it and extract the necessary 1 minute section and submit it for diagnosis.

**Comment by Dravion** [comment] 2019-01-04 12:19
At least other IMAP-Servers as Dovecot for example on Linux having this Problem to from time to time.
In fact, the IMAP RFC says, folder names a identified by its ASCII Name. Ok, as long as you do ASCII Characters in naming your folders, there will be no Problem, but if you use Nordic Umlauts or chineese
characters in Foldernames, it could be a Problem for such regional charactersets.

**Comment by martinknafve** [comment] 2019-08-16 14:44
Closing this issue since discussion has derailed, and there's not enough info provided to reproduce the issue. If you can reproduce the issue, enable logging, create a new issue and provide the logs.

**Closed by martinknafve** 2019-08-16 14:44 UTC
