### ISSUE TITLE
SURBL

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#133] opened 2015-11-16 21:58 UTC
**THIS ALSO APPLIES TO DNS-BL LOOKUPS**

I don't think that SURBL is working properly >> https://www.hmailserver.com/forum/viewtopic.php?f=7&t=28813

Looking at the source
https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/Common/AntiSpam/SURBL.cpp (line say 100 >> 130)

In my logs I get the DNS Query Fail every time a lookup occurs that doesn't find a match.
There is only ever one URL checked per SURBL (at most)
Very often (more than 2/3rds at a guess) the SURBL doesn't look like it is happening.

I suspect that the check for 'no listing' isn't working, and that when a message SURBL check come back with no match the DNS Query Fail is triggered and no further lookups are made.

For SURBL to score for Anti-SPAM, the FIRST url checked must match a SURBL entry.

For what it is worth, I get debug logging saying DNS Query failure for each of the Blacklist lookups too, if there is no match. This doesn't seem to impact on the ability of hMailserver to score SPAM though.

**Comment by jimimaseye** [comment] 2015-11-16 22:20
Im not so convinced Matt.  I agree that a "DNS query Failure" can happen, yes. Yesterday, I had a very weird situation where I was suffering MANY lookups failing immediately after upgrading to 564 (https://www.hmailserver.com/forum/viewtopic.php?f=7&t=28915) and during that (otherwise to be discussed to find the cause) problem I encountered many failures.  Example:

"DEBUG"	3528	"2015-11-15 09:14:06.044"	"SURBL: Found URL: symanteccloud.com"
"DEBUG"	3528	"2015-11-15 09:14:06.044"	"SURBL: 1 unique addresses found."
"DEBUG"	3528	"2015-11-15 09:14:06.044"	"SURBL: Lookup: symanteccloud.com.multi.surbl.org"
"TCPIP"	3528	"2015-11-15 09:14:06.044"	"DNS query failure. Query: symanteccloud.com.multi.surbl.org, Type: A/AAAA, DnsQuery return value: 11004. Message: The requested name is valid, but no data of the requested type was found"
"DEBUG"	3528	"2015-11-15 09:14:06.044"	"SURBL: DNS query failed."
(I had MANY of these also for the DNSBL lookups too).

However, during the day after rectifying getting the DNS lookups working again the same lookup was happening and completing:

"DEBUG"	2880	"2015-11-15 10:56:48.786"	"SURBL: Execute"
"DEBUG"	2880	"2015-11-15 10:56:48.786"	"SURBL: Found URL: symanteccloud.com"
"DEBUG"	2880	"2015-11-15 10:56:48.786"	"SURBL: 1 unique addresses found."
"DEBUG"	2880	"2015-11-15 10:56:48.786"	"SURBL: Lookup: symanteccloud.com.multi.surbl.org"
"DEBUG"	2880	"2015-11-15 10:56:48.786"	"SURBL: Match not found"

Note that it says "Match not found" and there ISNT a 'DNS failure'.

I then have another example where it looked up 2x urls within the email:


"DEBUG"	2876	"2015-11-15 11:14:03.560"	"SURBL: Execute"
"DEBUG"	2876	"2015-11-15 11:14:03.560"	"SURBL: Found URL: sanesecurity.com"
"DEBUG"	2876	"2015-11-15 11:14:03.560"	"SURBL: Found URL: hmailserver.com"
"DEBUG"	2876	"2015-11-15 11:14:03.560"	"SURBL: 2 unique addresses found."
"DEBUG"	2876	"2015-11-15 11:14:03.560"	"SURBL: Lookup: hmailserver.com.multi.surbl.org"
"DEBUG"	2876	"2015-11-15 11:14:03.560"	"SURBL: Lookup: sanesecurity.com.multi.surbl.org"
"DEBUG"	2876	"2015-11-15 11:14:03.560"	"SURBL: Match not found"

and yet again returns a "Match not found" (presumably meaning for both which would be correct)

My conclusion to this, and also from seeing the *wierdness* that occurred in the link I mentioned above (about 564 seemingly causing the DNS failures) was that the DNS Query failure is genuine in that it simply doesnt get the query to succeed (which is depicted with the error 11004) and not a coding issue.

**Comment by jimimaseye** [comment] 2015-11-16 22:25
(@Matt - might be worth considering you experience the same 'strangeness' regarding your DNS Query Failure frequency as I did in that linked discussion above.  And you will see from that how it was *rectified*.  Not pretty...or reasonable.)

**Comment by OutbackMatt** [comment] 2015-11-16 22:52
@jimimaseye, this DNS issue that I see in my logs is ONLY for RBL and SURBL lookups, and they look like they actually function, just return that it was a DNS failure rather than a 'NO MATCH'. I don't get DNS errors when SMTP or External POP3 are used.

It looks at the moment that the second last URL found in a mail message is the one searched for on SURBL servers - wierd+++

**Comment by jimimaseye** [comment] 2015-11-20 10:18
I agree that it is Blacklist lookups only.  I have since seen further 'weirdness' that lends further doubt to HMs behaving correctly despite the theoretic logic suggesting it just cant be the cause (ie, DNS is should be the sole cause IMO).  See this latest test: https://www.hmailserver.com/forum/viewtopic.php?p=180806#p180806

**Comment by OutbackMatt** [comment] 2015-11-20 23:53
further down that thread is note from another user suggesting that the following line doesn't check validity of the argument const sDNSBLHost before it is used. That could be the reason that this DNS lookup issue is intermittent for both DNSBL and SURBL

BLCheck.cpp / Line: 26

Code: Select all
bool BLCheck::ClientExistsInDNSBL(const IPAddress &sClientIP, const String &sDNSBLHost, const String &sExpectedResult).
{
}

**Comment by martinknafve** [comment] 2016-01-30 17:53
Fixed in upcoming 5.6.5 and 5.7.

**Closed by martinknafve** 2016-01-30 17:53 UTC
