### ISSUE TITLE
5.7 Serious bug with oMessages.DeleteByDBID - deletes EVERYTHING

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#216] opened 2017-02-18 12:18 UTC
DeletebyID deletes everything in the folder rather than just the individual message.

 I have just been testing and realised its causing big problems with this version of HMS in that it seems to delete everything in that folder even though it is calling the deletion of just 1 record.  Have tested with 2 different installs of 5.7 beta (from 'build') the latest being hMailServer-5.7.0-B2410-x86.

Problem doesnt exist in production 5.6.6 or 5.6.7 beta.

Full details:  https://www.hmailserver.com/forum/viewtopic.php?f=9&t=30954

**Comment by martinknafve** [comment] 2017-02-18 18:03
This will be fixed during the weekend. 

(Note that 5.7 is still alpha though)

**Comment by jimimaseye** [comment] 2017-02-18 19:33
Ok.  Yep - I understand its Alpha - I was testing it  (I only have it on a laptop - it would be dangerous if it had been missed and made it to public beta or production).

Am I right to report problems found on 5.7 builds or are you confident enough that your inbuilt tests would have found it eventually?

**Comment by martinknafve** [comment] 2017-02-19 09:49
I'm not 100% sure it would have been found actually. The API method is not used anywhere internally by hMailServer, but only with custom scripts. I've extended the test suite to cover this method as well.

**Comment by jimimaseye** [comment] 2017-02-19 11:46
Presumably you dont make changes to the Com during your updates and is reasonable to assume if it worked in the previous version then it should do now?  Or is this a wrong assumption and this problem highlights the dangers and its just not so?  (Do we need to do SERIOUS ComAPI testing then)?

**Comment by martinknafve** [comment] 2017-02-19 14:30
Most parts of the COM API are covered by the automated tests. In 5.7, there has been changes to how messages are cached in memory which was the cause of this bug. These changes have not been fully tested yet. I'm guessing (but I'm not sure) that this would have been found.

**Closed by martinknafve** 2017-02-19 14:30 UTC
