### ISSUE TITLE
Badly formed spf record of sender crashes hMailserver 5.7

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#453] opened 2023-03-12 01:21 UTC
https://www.hmailserver.com/forum/viewtopic.php?f=7&t=40159&p=245951#p245862

If sending domain has poorly configured spf record 5.7 crashes where 5.6 doesn't

can make it (5.7.x) crash really easy.... "v=spf1 mx redirect=77.32.128.0/18 redirect=77.32.192.0/19 ~all"

**Comment by martinknafve** [comment] 2023-03-12 12:22
I think it may be possible in 5.6 as well, even though I have not been able to reproduce it. I have pushed a fix for this, both for 5.6 and 5.7.

**Closed by martinknafve** 2023-03-12 12:22 UTC

**Comment by RvdHout** [comment] 2023-03-12 18:27
Yup, for some reason whatever i did i could **not** make 5.6.* crash, but 5.7.* cashed instantly
I couldn't debug RMSPF like i normally do with LOG_DEBUG()

Running included Tests stays a problem or maybe i just don't understand how to run these

**Comment by martinknafve** [comment] 2023-03-12 18:38
Can you clarify what you mean by "Running included Tests"? Do you mean specificially for RMSPF or all of the regression tests?

I have written instructions here:
https://github.com/hmailserver/hmailserver#running-tests

If those instructions doesn't work for you, maybe you can create a new issue with whatever error you're getting?

**Comment by RvdHout** [comment] 2023-03-12 18:48
Gonna give it a shot, (somewhere coming week) last time i checked the test i couldn't make them run, if i remember due to (missing) Vmware components

**Comment by RvdHout** [comment] 2023-03-13 11:22
> ### Running tests
> hMailServer source code contains a number of automated tests which excercises the basic functionality. When adding new features or fixing bugs, corresponding tests should be added. hMailServer tests are implemented using NUnit. To run them in Visual Studio, follow these steps:
> 
> NOTE: When running tests, your local hMailServer installation will be updated with test accounts. Existing domains and accounts are deleted. Each tests prepares the server configuration in different ways. In other words, do not run the automated tests in an environment where you need to preserve hMailServer data.
> 
> 1. Make sure hMailServer.exe is built and can be run. The tests will launch the service.
> 2. Open the test solution, \hmailserver\test\hMailServer Tests.sln
> 3. In Visual Studio, select Test Explorer from the View-menu.
> 4. Locate a test to run under "RegressionTests"
> 5. Right-click on a test or test category and select "Run".
> 
> You can also navigate to the source code for a test, right-click anywhere and select "Run Test(s)" to run it.

When at step 5 i choose "Run", nothing happens... but it doesn't show a error either

![image](https://user-images.githubusercontent.com/13403301/224687509-4f402a3b-8cf0-45d9-91e4-409a43309a63.png)

**Comment by RvdHout** [comment] 2023-03-13 19:28
@martinknafve 
Finally i have been able to run the Regression Tests, do all need to pass? I got 9 that failed
