### ISSUE TITLE
TLS 1.2 for MSSQL connection

### ISSUE THREAD

**Issue by kalevigit** [hmailserver/hmailserver#285] opened 2019-06-16 13:34 UTC
Please make it happen! 
I have both IIS, MSSQL and hMailserver in one box. And there is only a global setting for TLS.
![hmasil](https://user-images.githubusercontent.com/7052788/59564876-a1570c80-9054-11e9-8693-47cde8ef24f6.png)

https://www.chromestatus.com/feature/5654791610957824

**Comment by OutbackMatt** [comment] 2019-06-16 23:14
As answered in your other post (and PLEASE use the user forum for this type of query)

If you NEED to use MS SQL Server then you will need one of the private builds available on the hMailserver user forum. You could just change database.

Also, from my experience, MS SQL SERVER will allow different databases to have different settings. Your statement that there is ONLY a  global setting for TLS doesn't ring true to me, MS SQL Server allows users to have multiple SQL server engines installed, of differing versions and editions.

You haven't detailed which version or edition of MS SQL Server you are running, nor what operating system you are running. We would need more detail to help troubleshoot.

Go to the user forum please - http://www.hmailserver.com/forum/

**Comment by webprofusion-chrisc** [comment] 2019-08-14 11:42
Dupe of #186

**Comment by martinknafve** [comment] 2019-08-16 14:32
Closing this one since it's a dupe.

**Closed by martinknafve** 2019-08-16 14:32 UTC
