### ISSUE TITLE
Backup issue

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#446] opened 2022-09-16 04:33 UTC
If the software crashes while making a backup, you can no longer perform further backups until you remove the file \hMailServer\Logs\hmailserver_backup.log

It seems that this file is removed during a restart of the hMailserver service.

A possible workaround is to use the built in event 'OnBackupFailed' to remove that file when being triggered, but this will only work if the backup doesn't trigger a software crash and a minidump EVERY time a backup is run.

Perhaps before the hmailserver_backup.log is removed during startup, that the OnBackupFailed event be triggered first if that file exists

**Comment by RvdHout** [comment] 2022-09-16 23:53
As far as i know hmailserver_backup.log is not removed, what gave you that idea?

I just checked my hmailserver_backup.log (i remember i cleared that recently, but it holds 2 months)

```
2022-07-31 22:39:17.009	Backup started
﻿2022-07-31 22:39:17.024	Loading backup settings....
﻿2022-07-31 22:39:17.040	Backing up domains...
﻿2022-07-31 22:39:17.056	Backing up account info@...
﻿2022-07-31 22:39:17.058	**REPEATED FOR EVERY ACCOUNT**
﻿2022-07-31 22:39:18.790	Backing up data directory...
﻿2022-07-31 23:17:05.188	Backing up settings...
﻿2022-07-31 23:17:05.221	Writing XML file...
﻿2022-07-31 23:17:08.493	Compressing message files...
﻿2022-07-31 23:55:20.462	Backup completed successfully
﻿2022-08-31 22:49:31.056	Backup started
﻿2022-08-31 22:49:31.087	Loading backup settings....
﻿2022-08-31 22:49:31.119	Backing up domains...
﻿2022-08-31 22:49:31.119	Backing up account info@...
﻿2022-08-31 22:49:31.121	**REPEATED FOR EVERY ACCOUNT**
﻿2022-08-31 22:49:33.134	Backing up data directory...
﻿2022-08-31 23:26:51.434	Backing up settings...
﻿2022-08-31 23:26:51.466	Writing XML file...
﻿2022-08-31 23:26:54.116	Compressing message files...
﻿2022-09-01 00:14:25.465	Backup completed successfully

```

**Comment by OutbackMatt** [comment] 2022-09-17 07:26
Oh, you are correct

I delete mine during the OnBackupCompleted event 

What stops another backup from starting?
Is it that the last entry in the logs isn't "	Backup completed successfully"?

**Comment by RvdHout** [comment] 2022-09-17 08:38
In 'another' issue it was said the existence of the \DataBackup directory is the reason to not start another backup (FYI, which i think is deliberate, as the backup might still be in progress)

**Comment by mstenz** [comment] 2022-09-17 09:29
This is the reason: https://github.com/hmailserver/hmailserver/blob/74833dc91d83caf44071c68b89236e74dc1b747c/hmailserver/source/Server/Common/Application/BackupManager.cpp#L52
There is an internal variable saved when Backup is started. When Backup crashes this variable is still set and another Backup can only be executed when restarting the service (which sets the Variable to false again). Because there is no way to reset the value of the variable at runtime currently there is no other way. It has nothing to do with the existence of any logfile.

**Comment by RvdHout** [comment] 2022-09-17 09:46
> It has nothing to do with the existence of any logfile.

The existence of the \DataBackup doesn't matter either? Please try to be as complete as possible in your answers

**Comment by mstenz** [comment] 2022-09-17 10:11
> The existence of the \DataBackup doesn't matter either? Please try to be as complete as possible in your answers

I do not see anything about a DataBackup folder in the code. I just provided my experience, this doesn't mean the answer is complete or contains all aspects of it.

**Comment by mstenz** [comment] 2022-09-17 10:14
This is the script I use to fix the backup issue:

`@ECHO OFF
del /s /q /f "C:\_DATA\hMailServer\Logs\hmailserver_backup.log"

net stop hmailserver
net start hmailserver

del /s /q /f "C:\_DATA\hMailServer\Backup\backup.check"
del /s /q /f "C:\_DATA\hMailServer\Backup\_current\*.*"
rmdir /s /q "C:\_DATA\hMailServer\Backup\_current\DataBackup"
`

**Comment by martinknafve** [comment] 2023-03-12 14:13
This is a duplicate of https://github.com/hmailserver/hmailserver/issues/163.

**Closed by martinknafve** 2023-03-12 14:13 UTC
